[package]
name = "examples"
version = "0.0.8"
edition = "2021"

[[example]]
name = "in-memory"
path = "src/in_memory/main.rs"

[dependencies]
eventure = { path = "../sdk" }
uuid = { version = "1.8.0", features = ["v4"] }
colored = "2.1.0"
simple_logger = "5.0.0"
log = "0.4.21"
