[package]
name = "eventure"
description = "Event-Driven message handling library"
repository = "https://github.com/rust-lang-libs/eventure"
readme = "../README.md"
version = "0.0.1"
edition = "2021"
license-file = "../LICENSE"

[dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
