[package]
name = "eventure"
description = "Event-Driven messaging library for Rust"
repository = "https://github.com/rust-lang-libs/eventure"
readme = "../README.md"
version = "0.0.5"
edition = "2021"
license = "MIT"

[dependencies]
uuid = { version = "1.8.0", features = ["v4"] }
